### ISSUE TITLE
ThrottleMs parameter not accepted

### ISSUE THREAD

**Issue by lopezmas** [wgross/fswatcher-engine-event#11]
This command from the documentation does not accept the `-ThrottleMs 100` argument. Any idea why? 

`Register-EngineEvent -SourceIdentifier "myevent" -Action { $event | ConvertTo-Json | Write-Host } -ThrottleMs 100`

This is the error: 

```
Register-EngineEvent : A parameter cannot be found that matches parameter name 'ThrottleMs'.
At line:1 char:99
+ ... ent" -Action { $event | ConvertTo-Json | Write-Host } -ThrottleMs 100
+                                                           ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Register-EngineEvent], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RegisterEngineEventCommand
```

Is there another option to pass the ThrottleMs setting without using the GUI. 

Thanks,
Pablo.

**Comment by wgross** [comment]
Hi @lopezmas,
actually thats an error in the documention: These parameters are parameters to the ` New-FileSystemWatcher` command not to the `Register-EngineEvent` command, which is from PowerShell. 

I apologize for the confusion andwill push a fix of the readme.md this evening.
