### ISSUE TITLE
instructions for "how to install" seem missing

### ISSUE THREAD

**Issue by mi-hol** [wgross/fswatcher-engine-event#2]
Just typing the commands in pwsh 7.1.3 gives error, hence I assume an installation is pre-requisite but it not yet mentioned in README

```
New-FileSystemWatcher -SourceIdentifier "myevent" -Path c:\temp\
New-FileSystemWatcher: The term 'New-FileSystemWatcher' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

**Comment by wgross** [comment]
@mi-hol At first sorry for answering this late.... I haven't checked my github issues for a while.

Yes, you have to install powershell modules which aren't part of the original powershell distribution from MSFT.
The module is published at the Powershell Gallery an can be installed from there ```Install-Module``` cmdlet. The info-page of the module (https://www.powershellgallery.com/packages/FSWatcherEngineEvent/1.1) will give you the exact syntax and alternatives.

I'll update the README with some instructions in the near future as well.
