### ISSUE TITLE
Any way to make a FileSystemWatcher persistent

### ISSUE THREAD

**Issue by jagbarcelo** [wgross/fswatcher-engine-event#4]
We need to make use of your module in order to keep track of changes in a server's directory and make a synchronized copy of its contents but only for files matching certain criteria. Everything is already sorted out right now, except for the little detail that the call to New-FileSystemWatcher and Register-EngineEvent does not seem to live beyond the current PowerShell session.

We need to make those event subcriptions permanent, even beyond server reboots if possible.

If not, what is the best approach for achieving this? We were thinking about a scheduled task that runs at server reboots with something like this:

```
[...]
New-FileSystemWatcher -SourceIdentifier $WatcherId -Path $MonitoredFolder -IncludeSubdirectories
Register-EngineEvent -SourceIdentifier $WatcherId -Action { MyFileSystemWatcherEventHandler $event }
while($true) {}
```
That way the scheduled task will be left running forever and the PowerShell session will not be ended.
We would like a more elegant solution though.

**Comment by wgross** [comment]
Yes, the FS watcher can't live without a running powershell. 

A scheduled task seems to be the best option in my eyes to achieve what you want but the "active waiting" (while($true) { }) isn't desirable.

Have you tried to start the powershell with parameter -NoExit? I havn't tried this with the task scheduler but if I run 
```powershell
powershell  -NoExit -Command Test-Path c:\
```
from the prompt at WIN-R I'm getting a shell window with the result of Test-Path cmdlet that doesn't close after the command was run.

Combined woth other parameter like ```-NonInteractive```, ```-WindowStyle Hidden``` it should be possible to start a powershell instance running a file system watcher without having a while-loop eating CPU.

Please excuse my late answer, I hope the answer is still useful.
