### ISSUE TITLE
Errors within script block are invisible

### ISSUE THREAD

**Issue by Wardrop** [wgross/fswatcher-engine-event#5]
Hi,

I'm not sure if this is by design and I'm just missing something, but it seems any errors that happen inside the "Action" script block are swallowed up. Nothing is output to the console, and my attempts to try/catch and return the errors hasn't worked. It's easy to reproduce, just setup a watcher with an action that does say a divide by zero, and notice no errors reported to the console. 

How can I see errors within the script blocks as it's causing havoc with my scripts and making troubleshooting nearly impossible.

Cheers

**Comment by wgross** [comment]
HI @Wardrop, 
Please excuse my late response. Obvisously i'm inspecting my github issues not often enough.

I suppose this is how PowerShell handles thing in the 'background'. This may also depend on the PowerShell version.
I've tried this on the current PowerShell 7.3:

```PowerShell
# Imagine the following code is run for a file system event writing to the host directly, writing to Out-Default, warning stream and the error stream:

function generate-output {
  Write-Host "host"
  Write-Output "output"
  Write-Warning "warning"
  Write-Error "error"
}

# Now register an event handler:
# - the '2>$1' redirects error stream to 'success' stream
# - the 'Tee-Object' copies the success-streams content in a file and pipes everything to the 'Out-Default' additionally. This can be seen as a log file for the event handler.

Register-EngineEvent -SourceIdentifier "myevent" -Action { 
  generate-output 2>&1 | Tee-Object -FilePath c:\temp\tee-out -Append | Out-Default 
}
```

In console I see now all outputs:

```Powershell
host
output
WARNING: warning
generate-output: error
```

And the file `tee-out` has the following content from the success stream and the redirected error stream

```PowerShell
output

generate-output: error
```

I hope this helps to corner issues of errors in your script?

**Comment by Wardrop** [comment]
Thanks @wgross,
 
 Yeah I've done a bit of playing around, and I figured this would be a powershell thing rather than anything you're doing in-code, but I thought maybe you had a graceful solution. Surprising how `Write-Error` doesn't get emitted from the script block, though I think I know why.
 
 `Write-Error` is essentially the same as throwing an exception. If you have `$ErrorActionPreference = 'Stop'`, then it stops on `Write-Error`. So the solution for receiving errors within the event scriptblock seems to be adding `$ErrorActionPreference = 'Stop'` to the script block, and then wrapping all the logic within a try/catch statement. You can then do what you want with the error.

**Comment by wgross** [comment]
Ah OK, I didn't know that! 
"Again what learned" as we say in Germany :-)

**Comment by gbakeman** [comment]
Sorry to bump this everyone, but I also ran into an issue where PowerShell was quietly swallowing up errors with the `-Action` ScriptBlock and making it fairly difficult to diagnose what's wrong. This is especially tough with syntactical errors since PowerShell will stop the entire block without throwing anything.

If it's any help, I realized that the [`PSEventJob`](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.pseventjob) object that's returned from `New-FileSystemWatcher` contains a `JobStateInfo` property which can tell you if something is wrong, as well as an `Error` array that contains the exact exception. In my foreground script, I made a while loop to monitor for any issues and simply throw the exception when it's found.

```
    if ($WatcherJob.JobStateInfo.State.HasFlag([System.Management.Automation.JobState]::Failed)) {
        throw $WatcherJob.Error[0].Exception
    }
```

See also [this issue](https://github.com/PowerShell/vscode-powershell/issues/3401) if you're struggling with debugging Script Block code is VSCode - it's a notoriously difficult thing to do apparently.

**Comment by wgross** [comment]
> Sorry to bump this everyone, but I also ran into an issue where PowerShell was quietly swallowing up errors with the `-Action` ScriptBlock and making it fairly difficult to diagnose what's wrong. This is especially tough with syntactical errors since PowerShell will stop the entire block without throwing anything.
> 
> If it's any help, I realized that the [`PSEventJob`](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.pseventjob) object that's returned from `New-FileSystemWatcher` contains a `JobStateInfo` property which can tell you if something is wrong, as well as an `Error` array that contains the exact exception. In my foreground script, I made a while loop to monitor for any issues and simply throw the exception when it's found.
> 
> ```
>     if ($WatcherJob.JobStateInfo.State.HasFlag([System.Management.Automation.JobState]::Failed)) {
>         throw $WatcherJob.Error[0].Exception
>     }
> ```
> 
> See also [this issue](https://github.com/PowerShell/vscode-powershell/issues/3401) if you're struggling with debugging Script Block code is VSCode - it's a notoriously difficult thing to do apparently.

Thats a cool tip.. thank you!
