### ISSUE TITLE
filter and filewatch type

### ISSUE THREAD

**Issue by ericxin1982** [wgross/fswatcher-engine-event#9]
Hi @wgross 

If I only need to monitor specific extension in the target folder, how to do.
If I only need to monitor specific filewatch type, like created, how to do.

Thanks
Eric Xin

**Comment by wgross** [comment]
Hi @ericxin1982,
for watching specific extensions you may use the `-Filter` option: `-Filter *.txt` for example. Only one filter/extension can be specified.

For watching file change types use the parameter `-NotifyFilter`. Tab completion will present you possible values. Multiple values are specified as a comma separated list. For example: `-NotfyFilter FileName,DirectoryName,LastWrite`

Their meaning are explained in MS docs: https://learn.microsoft.com/en-us/dotnet/api/system.io.notifyfilters?view=net-7.0

**Comment by ericxin1982** [comment]
Thanks for your help.
